version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
  redis:
    container_name: my_redis
    image: 'redis:6.2-alpine'
    ports:
      - '6379:6379'
